# Generated by Django 6.1.1 on 2026-09-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="licence_number",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
