# Generated by Django 6.1.1 on 2026-09-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_rename_licence_number_driver_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
