# Generated by Django 6.1.1 on 2026-09-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0004_alter_driver_license_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={},
        ),
        migrations.RenameField(
            model_name="car",
            old_name="drivers",
            new_name="driver",
        ),
    ]
