# Generated by Django 6.1.1 on 2026-09-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0005_alter_driver_options_rename_drivers_car_driver"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ("model",)},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ("username",)},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ("name",)},
        ),
    ]
