# Generated by Django 6.1.1 on 2026-09-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0006_alter_car_options_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ("model",),
                "verbose_name": "car",
                "verbose_name_plural": "cars",
            },
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ("username",),
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "ordering": ("name",),
                "verbose_name": "manufacturer",
                "verbose_name_plural": "manufacturers",
            },
        ),
    ]
