# Generated by Django 6.1.1 on 2026-09-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0007_alter_car_options_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="driver",
            new_name="drivers",
        ),
    ]
